### ISSUE TITLE
Issues with Support commit

### ISSUE THREAD

**Issue by Mad-Spy** [Mad-Spy/Kill-Team-Age-of-Darkness#5]
- The Primary Category for a model denotes which category it appears under in the Roster Editor. The Primary category for all Support Operatives should be "Support Operative". _This is fixed_
- All models are missing some of their keywords.

**Chaplain**
- ~~Doesn't need a selection group for his melee weapon as it's his only choice. You can just link it directly to him with min1/max1 constraints.~~ _We need to be able to add (at least) a Phoenix Spear later, you can leave this._
- Missing all his abilities and unique action.

**Herald**
- Missing his abilities and unique actions.

**Lexicanium**
- Has Melee Rare Equipment incorrectly linked into its melee weapons group, but no actual melee weapons
- Has Ranged Rare weapons group linked into it, instead of a local "ranged weapons" group.
- Should be using shared versions of ranged weapons, not local.
- No abilities, unique action or psychic powers.

**Medicae**
- Model profile is named "Legion Chaplain".
- Should link shared bolt pistol
- No abilities or unique actions
- Has Jump Pack linked, but it doesn't actually have one.

**Moritat**
- Paired bolt pistols have incorrect profile (should only be 5 attacks for the Moritat and should also have a melee profile). _Same name, different profiles. Very annoying._
- Paired volkite serpentas is missing a whitespace character
- Paried volkite serpentas has bolt pistol profile
- Missing paired plasma pistols
- All of the above should be in a selection group
- Shouldn't have phosphex bombs
- Shouldn't have chainsword
- Blazing Fire has incorrect text. _I hate rules with matched names but different text; I will complain to Ossified._
- Missing Loner and Gunslinger abilities

**Comment by Tez205** [comment]
Fixed the Moritat
-  Added Loner special rule
-  Fixed Paired Bolt pistol ranged attacks
- Suggest we name the Paired Bolt Pistol (ranged) and a Paired Bolt Pistol (Melee), I understand how annoying it is XD.
- I don't know how to annotate Shared Plasma Profile. Just changed the named?
- Removed Chainsword from Phosphor from profile and added the *deflagrate special rule. 

I noticed that most of the updated profiles were in a different slot. Don't know if this was the change that you were working on or not. If I need to add the rules for the other guys in the Root Selection Entries rather than the Shared Selection Entries let me know.
